### ISSUE TITLE
Zoom Icon Misalignment and Firefox account icon bug

### ISSUE THREAD

**Issue by duckaleuze** [datguypiko/Firefox-Mod-Blur#148]
According to my testing, using cleaner_extensions_menu.css style 2 causes the Zoom icon in Firefox's menu to become misaligned with the other icons, also I noticed that using icons_in_main_menu.css adds a weird icon based on my mozilla account picture but is a bit messed up:

![365838948-0b981c54-0007-4f55-8517-60059cccc2dd](https://github.com/user-attachments/assets/1621b00c-e9f0-48fe-ae7b-0166f3511676)

above you can see my actual account picture and it's very different as you can see

-This happens both on latest Firefox release and nightly version

**Comment by datguypiko** [comment]
I fixed it. You can redownload here 
https://github.com/datguypiko/Firefox-Mod-Blur/tree/master/EXTRA%20MODS/Compact%20extensions%20menu/Style%202

**Comment by datguypiko** [comment]
So the icon stuff happens when you add a custom profile picture. Without custom it shows a normal round letter icon.

To fix it I just set it to be always static default icon. Firefox devs are going to introduce icons back in the future so this mod wont be needed anyway.

You can redownload here https://github.com/datguypiko/Firefox-Mod-Blur/tree/master/EXTRA%20MODS/Icon%20and%20Button%20Mods/Icons%20in%20main%20menu

All these fixes will be in next release later.

**Comment by duckaleuze** [comment]
thank you for your work :D
