### ISSUE TITLE
Too much padding on right side of the menu bar

### ISSUE THREAD

**Issue by rashedarman** [datguypiko/Firefox-Mod-Blur#64]
![Screenshot from 2023-07-07 08-54-12](https://github.com/datguypiko/Firefox-Mod-Blur/assets/78993606/73550129-e68a-4357-944e-f884a7fa1b71)

After removing the padding

![Screenshot from 2023-07-07 08-54-22](https://github.com/datguypiko/Firefox-Mod-Blur/assets/78993606/68c3bbc5-5b92-49c0-9291-71a70db56169)

It's not Librewolf specific issue. I also tried on a clean installation of default Firefox (114.0.2):

![image](https://github.com/datguypiko/Firefox-Mod-Blur/assets/78993606/4f9012e0-4c20-45db-b5f0-2df44ac874c2)

### Removing [this](https://github.com/datguypiko/Firefox-Mod-Blur/blob/317a3041b1a09dbbfb1dbefea319ba669431948b/userChrome.css#L982-L984) line fixes the issue for me.
But I have no clue how it'll effect windows or macOS.

Let me know if you have any questions. Thanks.

**Comment by datguypiko** [comment]
Linux? It's intentional because every distro is different. Some have more buttons some have less. You just need to modify the --firefoxcss-control-buttons-margin value depending on how big you need it to be.

Example: mint cinnamon
![Screenshot 2023-07-07 224658](https://github.com/datguypiko/Firefox-Mod-Blur/assets/61329159/40139b48-c80e-4092-97af-9dc13970b2fc)

Fedora GNOME
![Screenshot 2023-07-07 230258](https://github.com/datguypiko/Firefox-Mod-Blur/assets/61329159/34ae4115-0516-41b3-b91d-6977135072f4)

**Comment by rashedarman** [comment]
That totally makes sense. Thank you so much for clarification.
